apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: restaurant-app
data:
  DB_HOST: "mysql-service"
  DB_NAME: "restaurant_db"
  DB_PORT: "3306"
  NODE_ENV: "production"
  API_URL: "http://backend-service.restaurant-app.svc.cluster.local:8000"