apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: restaurant-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "restaurant_db"
  MYSQL_USER: "restaurant_user"
  MYSQL_PASSWORD: "root123"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: restaurant-app
type: Opaque
stringData:

  API_KEY: "your-api-key-here"  

